# Generated by Django 4.1.1 on 2022-11-05 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(blank=True, max_length=20, null=True)),
                ("track_name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=40)),
                ("type", models.CharField(max_length=50)),
                ("user_agent", models.CharField(max_length=200, null=True)),
                ("device_type", models.CharField(max_length=100, null=True)),
                ("browser", models.CharField(max_length=100, null=True)),
                ("os", models.CharField(max_length=100, null=True)),
                ("domain", models.CharField(max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "track_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="track.track"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackableEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("click", "Click"), ("pageview", "Pageview")],
                        max_length=10,
                    ),
                ),
                ("html_id", models.CharField(blank=True, max_length=100, null=True)),
                ("html_class", models.CharField(blank=True, max_length=100, null=True)),
                ("html_tag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "html_selector",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="track.track"
                    ),
                ),
            ],
        ),
    ]
