# Generated by Django 4.1.1 on 2022-11-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackableevent",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
