# Generated by Django 4.1.1 on 2022-11-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0002_trackableevent_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackevent",
            name="name",
        ),
        migrations.RemoveField(
            model_name="trackevent",
            name="type",
        ),
        migrations.AddField(
            model_name="trackevent",
            name="event",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="track.trackableevent",
            ),
            preserve_default=False,
        ),
    ]
